# Generated by Django 5.1 on 2024-08-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='Breakfast', max_length=100),
        ),
    ]
