# Generated by Django 5.1 on 2024-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
