# Generated by Django 5.1 on 2024-08-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0004_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
