# Generated by Django 5.1 on 2024-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0005_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=32)),
                ('cvv', models.CharField(max_length=3)),
                ('mm', models.CharField(max_length=2)),
                ('yy', models.CharField(max_length=2)),
                ('pay_done', models.BooleanField(default=False)),
            ],
        ),
    ]
