# Generated by Django 5.1 on 2024-08-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0007_reservation_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
