# Generated by Django 5.1 on 2024-08-31 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0009_delete_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=10)),
                ('guest_count', models.IntegerField()),
                ('guest_time', models.CharField(max_length=40)),
                ('guest_message', models.TextField()),
                ('reservation_time', models.DateField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_app.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
