# Generated by Django 5.1 on 2024-08-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0010_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=12),
        ),
    ]
