# Generated by Django 5.1 on 2024-09-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0011_alter_table_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
